In [1]:
import numpy as np

In [45]:
a = np.array([[1,2], [2,3], [3,4]])

In [47]:

a[:-1]

array([[1, 2],
       [2, 3]])

In [35]:
a[-1][]

array([3, 4])

In [33]:
b = np.array([[4, 6]])

In [44]:
np.append(a, a[-1][None,...], 0)

array([[1, 2],
       [2, 3],
       [3, 4],
       [3, 4]])

In [42]:
a[-1][None, ...]

array([[3, 4]])